name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: yartu/docs-whitepaper
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm install && npm run docs:build && cp CNAME docs/.vuepress/dist/
        BUILD_DIR: docs/.vuepress/dist/
